# Caso practico: arboles de decision

En este caso de uso practico se pretende resolver un problema de deteccion de malware en dispositivos Android mediante el analisis de trafico que genera el dispositivo meidnate el uso de arboles de decision.

## Dataset: deteccion de Malware en Android
**Descripcion**:

Android adware and general malware dataset (CIC-AAGM2017)

The sophisticated and advanced Android malware is able to identify the presence of the emulator used by the malware analyst and in response, alter its behaviour to evade detection. To overcome this issue, we installed the Android applications on the real device and captured its network traffic. 

CICAAGM dataset is captured by installing the Android apps on the real smartphones semi-automated. The dataset is generated from 1,900 applications with the following three categories:
1. Adware (250 apps)

    Airpush: Designed to deliver unsolicited advertisements to the user’s systems for information stealing.

    Dowgin: Designed as an advertisement library that can also steal the user’s information.

    Kemoge: Designed to take over a user’s Android device. This adware is a hybrid of botnet and disguises itself as popular apps via repackaging.

    Mobidash: Designed to display ads and to compromise user’s personal information.

    Shuanet: Similar to Kemoge, Shuanet is also designed to take over a user’s device.

2. General Malware (150 apps)

    AVpass: Designed to be distributed in the guise of a Clock app.

    FakeAV: Designed as a scam that tricks user to purchase a full version of the software in order to re-mediate non-existing infections.

    FakeFlash/FakePlayer: Designed as a fake Flash app in order to direct users to a website (after successfully installed).

    GGtracker: Designed for SMS fraud (sends SMS messages to a premium-rate number) and information stealing.

    Penetho: Designed as a fake service (hacktool for Android devices that can be used to crack the WiFi password). The malware is also able to infect the user’s computer via infected email attachment, fake updates, external media and infected documents.

3. Benign (1,500 apps)

    2015 GooglePlay market (top free popular and top free new)

    2016 GooglePlay market (top free popular and top free new)

License

The CICAAGM dataset consists of the following items is publicly available for researchers.

    .pcap files – the network traffic of both the malware and benign (20% malware and 80% benign)

    .csv files - the list of extracted network traffic features generated by the CIC-flowmeter

If you are using our dataset, you should cite our related paper that outlines the details of the dataset and its underlying principles:

    Arash Habibi Lashkari, Andi Fitriah A. Kadir, Hugo Gonzalez, Kenneth Fon Mbah and Ali A. Ghorbani, “Towards a Network-Based Framework for Android Malware Detection and Characterization”, In the proceeding of the 15th International Conference on Privacy, Security and Trust, PST, Calgary, Canada, 2017.

### Ficheros de datos

1. pcap files - The traffic of both the malware and bening **(20% malware and 80% benings)**
2. <span style="color:green">.csv files </span> - the list of extracted network traffic features generated by the CIC-flowmetter

## Imports

In [23]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import confusion_matrix,recall_score,f1_score,precision_score
from pandas import DataFrame

### Funciones auxiliares

In [24]:
# Construir una funcion que realice el particionado completo 
def train_val_test_split(df,rstate=42,shuffle=True,stratify=None):
    strat=df[stratify] if stratify else None 
    train_set,test_set = train_test_split(
        df,test_size = 0.4, random_state=rstate,shuffle=shuffle,stratify=strat
    )
    strat = test_set[stratify] if stratify else None
    val_set,test_set = train_test_split(
        test_set,test_size=0.5,random_state=rstate,shuffle=shuffle,stratify=strat
    )
    return train_set,val_set,test_set

In [25]:
def remove_labels(df,label_name):
    x=df.drop(label_name,axis=1)
    y=df[label_name].copy() 
    return(x,y)

In [26]:
def evaluate(y_pred,y,y_prep_pred,y_prep,metric):
    print(metric.__name__,"WITHOUT preparation:",metric(y_pred,y,average="weighted"))
    print(metric.__name__,"WITH preparation:",metric(y_prep_pred,y_pred,average="weighted"))

## 1.-Lectura del dataset

In [27]:
df = pd.read_csv('./DataSet/TotalFeatures-ISCXFlowMeter.csv')

In [28]:
df.head(10)

,duration,total_fpackets,total_bpackets,total_fpktl,total_bpktl,min_fpktl,min_bpktl,max_fpktl,max_bpktl,mean_fpktl,...,mean_idle,max_idle,std_idle,FFNEPD,Init_Win_bytes_forward,Init_Win_bytes_backward,RRT_samples_clnt,Act_data_pkt_forward,min_seg_size_forward,calss
0,1020586,668,1641,35692,2276876,52,52,679,1390,53.431138,...,0.0,-1,0.0,2,4194240,1853440,1640,668,32,benign
1,80794,1,1,75,124,75,124,75,124,75.000000,...,0.0,-1,0.0,2,0,0,0,1,0,benign
2,998,3,0,187,0,52,-1,83,-1,62.333333,...,0.0,-1,0.0,4,101888,-1,0,3,32,benign
3,189868,9,9,1448,6200,52,52,706,1390,160.888889,...,0.0,-1,0.0,2,4194240,2722560,8,9,32,benign
4,110577,4,6,528,1422,52,52,331,1005,132.000000,...,0.0,-1,0.0,2,155136,31232,5,4,32,benign
5,261876,7,6,1618,882,52,52,730,477,231.142857,...,0.0,-1,0.0,2,4194240,926720,3,7,32,benign
6,14,2,0,104,0,52,-1,52,-1,52.000000,...,0.0,-1,0.0,3,5824,-1,0,2,32,benign
7,29675,1,1,71,213,71,213,71,213,71.000000,...,0.0,-1,0.0,2,0,0,0,1,0,benign
8,806635,4,0,239,0,52,-1,83,-1,59.750000,...,0.0,-1,0.0,5,107008,-1,0,4,32,benign
9,56620,3,2,1074,719,52,52,592,667,358.000000,...,0.0,-1,0.0,3,128512,10816,1,3,32,benign

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 631955 entries, 0 to 631954
Data columns (total 80 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   duration                 631955 non-null  int64
 1   total_fpackets           631955 non-null  int64
 2   total_bpackets           631955 non-null  int64
 3   total_fpktl              631955 non-null  int64
 4   total_bpktl              631955 non-null  int64
 5   min_fpktl                631955 non-null  int64
 6   min_bpktl                631955 non-null  int64
 7   max_fpktl                631955 non-null  int64
 8   max_bpktl                631955 non-null  int64
 9   mean_fpktl               631955 non-null  float64
 10  mean_bpktl               631955 non-null  float64
 11  std_fpktl                631955 non-null  float64
 12  std_bpktl                631955 non-null  float64
 13  total_fiat               631955 non-null  int64
 14  total_biat               631955 non-null  int64
 15  min_fiat                 631955 non-null  int64
 16  min_biat                 631955 non-null  int64
 17  max_fiat                 631955 non-null  int64
 18  max_biat                 631955 non-null  int64
 19  mean_fiat                631955 non-null  float64
 20  mean_biat                631955 non-null  float64
 21  std_fiat                 631955 non-null  float64
 22  std_biat                 631955 non-null  float64
 23  fpsh_cnt                 631955 non-null  int64
 24  bpsh_cnt                 631955 non-null  int64
 25  furg_cnt                 631955 non-null  int64
 26  burg_cnt                 631955 non-null  int64
 27  total_fhlen              631955 non-null  int64
 28  total_bhlen              631955 non-null  int64
 29  fPktsPerSecond           631955 non-null  float64
 30  bPktsPerSecond           631955 non-null  float64
 31  flowPktsPerSecond        631955 non-null  float64
 32  flowBytesPerSecond       631955 non-null  float64
 33  min_flowpktl             631955 non-null  int64
 34  max_flowpktl             631955 non-null  int64
 35  mean_flowpktl            631955 non-null  float64
 36  std_flowpktl             631955 non-null  float64
 37  min_flowiat              631955 non-null  int64
 38  max_flowiat              631955 non-null  int64
 39  mean_flowiat             631955 non-null  float64
 40  std_flowiat              631955 non-null  float64
 41  flow_fin                 631955 non-null  int64
 42  flow_syn                 631955 non-null  int64
 43  flow_rst                 631955 non-null  int64
 44  flow_psh                 631955 non-null  int64
 45  flow_ack                 631955 non-null  int64
 46  flow_urg                 631955 non-null  int64
 47  flow_cwr                 631955 non-null  int64
 48  flow_ece                 631955 non-null  int64
 49  downUpRatio              631955 non-null  float64
 50  avgPacketSize            631955 non-null  float64
 51  fAvgSegmentSize          631955 non-null  float64
 52  fHeaderBytes             631955 non-null  int64
 53  fAvgBytesPerBulk         631955 non-null  int64
 54  fAvgPacketsPerBulk       631955 non-null  int64
 55  fAvgBulkRate             631955 non-null  int64
 56  bVarianceDataBytes       631955 non-null  float64
 57  bAvgSegmentSize          631955 non-null  int64
 58  bAvgBytesPerBulk         631955 non-null  int64
 59  bAvgPacketsPerBulk       631955 non-null  int64
 60  bAvgBulkRate             631955 non-null  int64
 61  sflow_fpacket            631955 non-null  int64
 62  sflow_fbytes             631955 non-null  int64
 63  sflow_bpacket            631955 non-null  int64
 64  sflow_bbytes             631955 non-null  int64
 65  min_active               631955 non-null  int64
 66  mean_active              631955 non-null  float64
 67  max_active               631955 non-null  int64
 68  std_active               631955 non-null  float64
 69  min_idle                 631955 non-null  int64
 70  mean_idle                631955 non-null  float64
 71  max_idle                 631955 non-null  int64
 72  std_idle                 631955 non-null  float64
 73  FFNEPD                   631955 non-null  int64
 74  Init_Win_bytes_forward   631955 non-null  int64
 75  Init_Win_bytes_backward  631955 non-null  int64
 76  RRT_samples_clnt         631955 non-null  int64
 77  Act_data_pkt_forward     631955 non-null  int64
 78  min_seg_size_forward     631955 non-null  int64
 79  calss                    631955 non-null  str
dtypes: float64(24), int64(55), str(1)
memory usage: 389.4 MB

In [30]:
df['calss'].value_counts()

calss
benign            471597
asware            155613
GeneralMalware      4745
Name: count, dtype: int64

### Buscando correlaciones

In [31]:
# copiar el dataframe y transformar la variable de salida a numerica para calcular correlaciones
X=df.copy()
X['calss']=X['calss'].factorize()[0]

In [32]:
# Columnar correlaciones 
corr_matrix = X.corr()
corr_matrix['calss'].sort_values(ascending=False)

calss                     1.000000
flow_fin                  0.286175
min_seg_size_forward      0.258352
Init_Win_bytes_forward    0.129425
std_fpktl                 0.123758
                            ...
furg_cnt                       NaN
burg_cnt                       NaN
flow_urg                       NaN
flow_cwr                       NaN
flow_ece                       NaN
Name: calss, Length: 80, dtype: float64

In [33]:
X.corr()

,duration,total_fpackets,total_bpackets,total_fpktl,total_bpktl,min_fpktl,min_bpktl,max_fpktl,max_bpktl,mean_fpktl,...,mean_idle,max_idle,std_idle,FFNEPD,Init_Win_bytes_forward,Init_Win_bytes_backward,RRT_samples_clnt,Act_data_pkt_forward,min_seg_size_forward,calss
duration,1.000000,0.004837,0.004011,0.001673,0.003518,-0.064100,-0.027231,0.008761,0.042925,-0.043746,...,0.998901,0.999458,0.047582,0.016532,0.027610,0.029712,0.003785,0.004838,0.082955,0.067066
total_fpackets,0.004837,1.000000,0.924622,0.425756,0.904007,-0.018958,0.005252,0.024685,0.086255,-0.007910,...,0.001614,0.002267,0.017229,0.016089,0.050201,0.059224,0.902713,0.999866,0.018198,0.018377
total_bpackets,0.004011,0.924622,1.000000,0.156780,0.997268,-0.017667,0.006912,0.018170,0.086886,-0.016104,...,0.000922,0.001617,0.016230,-0.000493,0.048190,0.058435,0.997580,0.924746,0.015124,0.019430
total_fpktl,0.001673,0.425756,0.156780,1.000000,0.090082,-0.003099,0.000803,0.021278,0.022088,0.022409,...,0.000335,0.000609,0.009896,0.001657,0.013283,0.015991,0.088422,0.425789,0.005477,0.000679
total_bpktl,0.003518,0.904007,0.997268,0.090082,1.000000,-0.014926,0.005966,0.012560,0.079905,-0.017328,...,0.000812,0.001452,0.014336,-0.000293,0.043571,0.053134,0.999616,0.904129,0.012139,0.019838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Init_Win_bytes_backward,0.029712,0.059224,0.058435,0.015991,0.053134,-0.268444,0.038319,0.429893,0.593143,-0.030004,...,0.026959,0.029512,0.097316,-0.052507,0.811204,1.000000,0.056761,0.059242,0.333701,0.069405
RRT_samples_clnt,0.003785,0.902713,0.997580,0.088422,0.999616,-0.016659,0.006156,0.015727,0.084280,-0.017595,...,0.000893,0.001560,0.015200,-0.000437,0.046784,0.056761,1.000000,0.902834,0.014299,0.019679
Act_data_pkt_forward,0.004838,0.999866,0.924746,0.425789,0.904129,-0.018947,0.005264,0.024705,0.086278,-0.007893,...,0.001617,0.002269,0.017233,0.000734,0.050220,0.059242,0.902834,1.000000,0.018229,0.018391
min_seg_size_forward,0.082955,0.018198,0.015124,0.005477,0.012139,-0.686154,-0.189824,-0.074763,0.217989,-0.524024,...,0.077943,0.079324,0.048803,0.052177,0.394743,0.333701,0.014299,0.018229,1.000000,0.258352
calss,0.067066,0.018377,0.019430,0.000679,0.019838,-0.271343,0.027032,-0.040019,0.073212,-0.211892,...,0.066348,0.066965,0.022790,0.018300,0.129425,0.069405,0.019679,0.018391,0.258352,1.000000

In [34]:
# Se puede llegar a valorar quedarse con aquellas que tienen mayor correlacion
corr_matrix[corr_matrix["calss"] > 0.05]

,duration,total_fpackets,total_bpackets,total_fpktl,total_bpktl,min_fpktl,min_bpktl,max_fpktl,max_bpktl,mean_fpktl,...,mean_idle,max_idle,std_idle,FFNEPD,Init_Win_bytes_forward,Init_Win_bytes_backward,RRT_samples_clnt,Act_data_pkt_forward,min_seg_size_forward,calss
duration,1.000000,0.004837,0.004011,0.001673,0.003518,-0.064100,-0.027231,0.008761,0.042925,-0.043746,...,0.998901,0.999458,0.047582,0.016532,0.027610,0.029712,0.003785,0.004838,0.082955,0.067066
max_bpktl,0.042925,0.086255,0.086886,0.022088,0.079905,-0.277317,0.275923,0.492194,1.000000,-0.018358,...,0.035413,0.038732,0.127548,-0.044916,0.586742,0.593143,0.084280,0.086278,0.217989,0.073212
mean_bpktl,0.025117,0.139142,0.151761,0.018954,0.146437,-0.280648,0.465208,0.342392,0.895712,-0.096195,...,0.018533,0.021519,0.114949,-0.045442,0.452735,0.478823,0.150252,0.139172,0.122226,0.064753
std_fpktl,0.039350,0.010172,0.002331,0.011416,-0.003162,-0.245792,0.052877,0.817873,0.564243,0.259588,...,0.031418,0.033978,0.096844,-0.020885,0.558249,0.532900,0.000140,0.010182,0.301237,0.123758
std_bpktl,0.048743,0.020324,0.014005,0.007763,0.007768,-0.225143,0.035371,0.534532,0.941626,0.051756,...,0.042562,0.045450,0.113854,-0.033991,0.594790,0.577954,0.012050,0.020335,0.276055,0.072953
total_fiat,0.943898,0.002190,0.001718,0.000708,0.001546,-0.049879,-0.031218,-0.029233,-0.005961,-0.048869,...,0.943668,0.943339,0.015254,0.020302,-0.011637,-0.016421,0.001615,0.002190,0.065124,0.064770
min_fiat,0.841692,-0.001975,-0.002172,-0.000746,-0.001820,-0.040046,-0.036619,-0.052289,-0.035963,-0.053811,...,0.843330,0.842512,-0.005389,0.015316,-0.027350,-0.033944,-0.002037,-0.001974,0.051853,0.074491
max_fiat,0.943438,-0.000420,-0.000714,-0.000389,-0.000548,-0.046977,-0.032630,-0.032606,-0.009878,-0.049032,...,0.944412,0.943971,0.012557,0.017756,-0.012317,-0.016206,-0.000644,-0.000418,0.061285,0.064875
mean_fiat,0.918036,-0.001970,-0.002241,-0.000728,-0.001907,-0.042455,-0.036056,-0.048712,-0.032412,-0.052892,...,0.919653,0.918797,-0.003523,0.016958,-0.025823,-0.032466,-0.002113,-0.001968,0.055151,0.071397
std_flowpktl,0.036942,0.087741,0.087307,0.024298,0.080666,-0.262968,0.338513,0.631466,0.911584,0.095976,...,0.030013,0.033100,0.120257,-0.035737,0.580266,0.586355,0.084725,0.087764,0.219346,0.119375
min_flowiat,0.841666,-0.001972,-0.002169,-0.000744,-0.001816,-0.039980,-0.036623,-0.052221,-0.035917,-0.053744,...,0.843311,0.842493,-0.005388,0.015323,-0.027316,-0.033903,-0.002033,-0.001971,0.051763,0.074452
max_flowiat,0.999457,0.002273,0.001623,0.000611,0.001458,-0.061004,-0.028758,0.005240,0.038796,-0.043865,...,0.999602,1.000000,0.043309,0.013884,0.026609,0.029591,0.001566,0.002276,0.079417,0.066992
mean_flowiat,0.949299,-0.002050,-0.002292,-0.000748,-0.001972,-0.044032,-0.035728,-0.048943,-0.031180,-0.054610,...,0.950940,0.950117,-0.002380,0.016349,-0.024163,-0.030175,-0.002169,-0.002048,0.056882,0.072549
flow_fin,0.068154,0.005461,0.004894,-0.001464,0.005112,-0.408271,-0.155843,-0.126824,0.035163,-0.356749,...,0.071426,0.071654,0.017388,0.048678,0.238759,0.204597,0.005338,0.005479,0.551140,0.286175
flow_syn,0.020298,0.045730,0.043305,0.012057,0.039253,-0.268203,0.010317,0.388110,0.537187,-0.043379,...,0.014644,0.018113,0.112752,0.012415,0.890695,0.729790,0.042069,0.045747,0.370962,0.115044
flow_rst,-0.003951,-0.004097,-0.004343,-0.001550,-0.003732,-0.098533,-0.063549,-0.106686,-0.040593,-0.121735,...,-0.002382,-0.002685,-0.009004,0.028905,-0.067341,-0.064202,-0.004112,-0.004092,0.064160,0.058715
bVarianceDataBytes,0.042755,0.012731,0.006942,0.004947,0.002038,-0.184458,0.027897,0.428040,0.900543,0.019958,...,0.039000,0.041333,0.094613,-0.030463,0.516196,0.507734,0.005591,0.012739,0.231281,0.056086
bAvgSegmentSize,0.025105,0.139151,0.151778,0.018949,0.146457,-0.280510,0.465396,0.342137,0.895560,-0.096229,...,0.018527,0.021512,0.114916,-0.045430,0.452305,0.478400,0.150270,0.139180,0.121997,0.064755
min_active,0.997972,0.002195,0.001495,0.000434,0.001410,-0.058989,-0.028861,0.001318,0.033057,-0.044135,...,0.999746,0.998771,-0.005581,0.012340,0.022190,0.025199,0.001474,0.002198,0.077047,0.066001
mean_active,0.998911,0.002580,0.001852,0.000650,0.001724,-0.059924,-0.028800,0.003287,0.035932,-0.043954,...,0.999998,0.999603,0.016879,0.012854,0.024362,0.027367,0.001808,0.002582,0.078161,0.066552
max_active,0.999465,0.003261,0.002592,0.000919,0.002409,-0.061083,-0.028773,0.005583,0.039286,-0.043762,...,0.999596,0.999998,0.043430,0.013858,0.027031,0.029961,0.002520,0.003264,0.079542,0.067178
min_idle,0.997952,0.001258,0.000610,0.000113,0.000544,-0.058793,-0.028867,0.001028,0.032544,-0.044117,...,0.999743,0.998762,-0.005776,0.012279,0.021657,0.024794,0.000605,0.001261,0.076794,0.065804
mean_idle,0.998901,0.001614,0.000922,0.000335,0.000812,-0.059748,-0.028819,0.002983,0.035413,-0.043962,...,1.000000,0.999601,0.016744,0.012852,0.023865,0.026959,0.000893,0.001617,0.077943,0.066348
max_idle,0.999458,0.002267,0.001617,0.000609,0.001452,-0.060904,-0.028800,0.005244,0.038732,-0.043786,...,0.999601,1.000000,0.043323,0.013880,0.026525,0.029512,0.001560,0.002269,0.079324,0.066965
Init_Win_bytes_forward,0.027610,0.050201,0.048190,0.013283,0.043571,-0.323350,0.007284,0.409109,0.586742,-0.075007,...,0.023865,0.026525,0.095880,-0.021448,1.000000,0.811204,0.046784,0.050220,0.394743,0.129425
Init_Win_bytes_backward,0.029712,0.059224,0.058435,0.015991,0.053134,-0.268444,0.038319,0.429893,0.593143,-0.030004,...,0.026959,0.029512,0.097316,-0.052507,0.811204,1.000000,0.056761,0.059242,0.333701,0.069405
min_seg_size_forward,0.082955,0.018198,0.015124,0.005477,0.012139,-0.686154,-0.189824,-0.074763,0.217989,-0.524024,...,0.077943,0.079324,0.048803,0.052177,0.394743,0.333701,0.014299,0.018229,1.000000,0.258352
calss,0.067066,0.018377,0.019430,0.000679,0.019838,-0.271343,0.027032,-0.040019,0.073212,-0.211892,...,0.066348,0.066965,0.022790,0.018300,0.129425,0.069405,0.019679,0.018391,0.258352,1.000000

### 2.- Division del dataset

In [35]:
train_set,val_set,test_set = train_val_test_split(X)

In [36]:
x_train,y_train = remove_labels(train_set,'calss')
x_val,y_val = remove_labels(val_set,'calss')
x_test,y_test = remove_labels(test_set,'calss')

### 4.- Escalado del dataset

Es importante comprender que los arboles de decision son algortimos que **no requieren demasiada preparacion de datos** correctamente, no require de un escalado o normalizacion. En este ejercicio se va a realizar el escalado con el dataset y se van a comprar los resultados con el conjunto de datos sin escalar. De esta forma se demuestra como aplicar procesamientos como el escaldo puede llegar a afectar el rendimiento del modelo.

In [37]:
scaler = RobustScaler()
x_train_scaled = scaler.fit_transform(x_train)

In [40]:
scaler = RobustScaler
scaler()
x_test_scaled = scaler.fit_transform(x_test)

TypeError: TransformerMixin.fit_transform() missing 1 required positional argument: 'X'

In [41]:
scaler = RobustScaler()
x_val_scaled = scaler.fit_transform(x_val)

In [42]:
# Transformar a un dataframe de pandas
x_test_scaled = pd.DataFrame(x_train_scaled,columns=x_train.columns, index=x_train.index)

In [43]:
x_train_scaled[:10]

array([[-1.36463439e-02,  0.00000000e+00,  1.00000000e+00,
        -3.10055866e-01,  1.55688623e+00,  3.75000000e-01,
         4.92452830e+00, -2.71002710e-02,  2.25000000e+00,
        -3.28947368e-02,  2.49400480e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  6.83331452e+01,
         1.27926531e+02,  6.76930729e+01,  1.10512958e+02,
         3.75000000e-01,  2.67567568e-01,  1.86900958e-01,
         1.44993568e+00,  2.88097492e-02, -1.83413248e-02,
        -2.06761234e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -6.66666667e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.56164384e+00,  1.86900958e-01,
        -3.28947368e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.50000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -2.86341770e-01,
         1.10500901e-05,  0.00000000e+00,  0.00000000e+00,
        -1.00000000e+00],
       [-1.39258652e-02,  0.00000000e+00,  0.00000000e+00,
         6.64804469e-01,  0.00000000e+00,  6.60714286e+00,
         0.00000000e+00,  9.18699187e-01,  0.00000000e+00,
         1.11513158e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -8.69155475e-03,
         0.00000000e+00, -6.92712862e-03, -8.81024752e-03,
         6.60714286e+00,  7.05405405e-01,  1.00319489e+00,
        -1.10492179e-02, -2.36630383e-04, -1.87292460e-02,
        -2.17373037e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -6.66666667e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00319489e+00,
         1.11513158e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -2.86341770e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.00000000e+00],
       [-1.39258652e-02,  0.00000000e+00,  0.00000000e+00,
         7.03910615e-01,  0.00000000e+00,  6.85714286e+00,
         0.00000000e+00,  9.56639566e-01,  0.00000000e+00,
         1.16118421e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -8.69155475e-03,
         0.00000000e+00, -6.92712862e-03, -8.81024752e-03,
         6.85714286e+00,  7.43243243e-01,  1.04792332e+00,
        -1.10492179e-02, -2.36630383e-04, -1.87292460e-02,
        -2.17373037e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -6.66666667e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.04792332e+00,
         1.16118421e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -2.86341770e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.00000000e+00],
       [-2.73246332e-04,  0.00000000e+00,  1.00000000e+00,
        -3.63128492e-01,  2.72455090e+00,  3.57142857e-02,
         8.60377358e+00, -7.85907859e-02,  3.93103448e+00,
        -9.53947368e-02,  4.36450839e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  1.39052710e+00,
         2.61914511e+00,  1.37915067e+00,  3.44994885e+00,
         3.57142857e-02,  7.94594595e-01,  4.68051118e-01,
         3.12193503e+00,  1.41564127e+00,  1.80134485e-04,
         3.00937737e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -6.66666667e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  8.42592593e+00,  4.68051118e-01,
        -9.53947368e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.37500000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -2.86341770e-01,
         1.10500901e-05,  0.00000000e+00,  0.00000000e+00,
        -1.00000000e+00],
       [-1.39258652e-02,  0.00000000e+00,  0.00000000e+00,
         6.64804469e-01,  0.00000000e+00,  6.60714286e+00,
         0.00000000e+00,  9.18699187e-01,  0.00000000e+00,
         1.11513158e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -8.69155475e-03,
         0.00000000e+00, -6.92712862e-03, -8.81024752e-03,
         6.60714286e+00,  7.05405405e-01,  1.00319489e+00,
        -1.10492179e-02, -2.36630383e-04, -1.87292460e-02,
        -2.17373037e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -6.66666667e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00319489e+00,
         1.11513158e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -2.86341770e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.00000000e+00],
       [ 3.44219266e+01,  1.50000000e+00,  4.00000000e+00,
         1.55865922e+00,  3.86826347e+00,  0.00000000e+00,
         1.00000000e+00,  1.34146341e+00,  4.16379310e+00,
         3.37171053e-01,  1.54916067e+00,  1.68951572e+01,
         2.13699165e+02,  3.36087730e-01,  6.03319990e+07,
         1.06285714e+03,  1.12620000e+04,  2.89292762e-01,
         6.02288090e+07,  4.67228184e-01,  2.01000000e+07,
         2.77774117e+00,  3.47000000e+07,  1.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.50000000e+00,  4.00000000e+00, -6.47258844e-03,
         4.15360012e-03, -4.72900188e-03, -5.07088881e-03,
         0.00000000e+00,  1.12702703e+00,  2.09265176e-01,
         2.43695552e+00,  2.72361571e-01,  4.75622163e+01,
         1.86544004e+01,  1.23057301e+03,  1.00000000e+00,
         2.00000000e+00,  0.00000000e+00,  2.00000000e+00,
         1.66666667e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  8.70619946e-01,  2.09265176e-01,
         3.37171053e-01,  1.50000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  4.56673333e+04,
         1.54807692e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  4.00000000e+00,  1.42692308e+01,
         4.00000000e+00,  6.46000000e+02,  5.91748751e+01,
         4.19261309e+01,  4.16965617e+01,  0.00000000e+00,
         5.96571016e+01,  4.81167719e+01,  4.75809456e+01,
         0.00000000e+00,  0.00000000e+00,  1.34210416e+01,
         1.26575798e+01,  3.00000000e+00,  1.50000000e+00,
         0.00000000e+00],
       [-1.38049295e-02,  5.00000000e-01,  0.00000000e+00,
        -1.36871508e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -5.09868421e-02,  0.00000000e+00,  1.41372226e+00,
         0.00000000e+00,  5.02667457e-04,  0.00000000e+00,
         1.52142857e+01,  0.00000000e+00,  8.06821238e-04,
         0.00000000e+00,  2.09642051e-03,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.00000000e-01,  0.00000000e+00,  3.15911120e+02,
         0.00000000e+00,  1.56469488e+02,  1.03552510e+02,
         0.00000000e+00, -2.10810811e-01, -1.29392971e-01,
         2.30900903e-01,  1.23639375e-02, -1.85609625e-02,
        -2.12781808e-02,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -1.29392971e-01,
        -5.09868421e-02,  5.00000000e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00, -8.07362476e-02,
         0.00000000e+00,  0.00000000e+00,  5.00000000e-01,
         0.00000000e+00],
       [ 1.75787340e+01,  5.00000000e-01,  0.00000000e+00,
        -5.02793296e-02,  0.00000000e+00,  5.53571429e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  6.45609319e-02,
         0.00000000e+00,  7.31236040e+01,  0.00000000e+00,
         2.20284864e+06,  0.00000000e+00,  1.16818174e+02,
         0.00000000e+00,  3.04574301e+02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  2.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.00000000e-01,  0.00000000e+00, -6.51985370e-03,
         0.00000000e+00, -5.85147593e-03, -7.93487062e-03,
         5.53571429e-01, -2.10810811e-01, -7.98722045e-02,
         0.00000000e+00,  1.82441298e+03,  2.43467360e+01,
         6.66810239e+01,  0.00000000e+00,  2.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  2.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -7.98722045e-02,
         0.00000000e+00,  5.00000000e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.00000000e+00,  3.19230769e+00,
         0.00000000e+00,  0.00000000e+00,  3.02313837e+01,
         2.13795502e+01,  2.13020265e+01,  0.00000000e+00,
         3.05494777e+01,  2.46178833e+01,  2.43654652e+01,
         0.00000000e+00,  1.00000000e+00,  6.33758628e-02,
         0.00000000e+00,  0.00000000e+00,  5.00000000e-01,
         0.00000000e+00],
       [-1.39258652e-02,  0.00000000e+00,  0.00000000e+00,
         7.03910615e-01,  0.00000000e+00,  6.85714286e+00,
         0.00000000e+00,  9.56639566e-01,  0.00000000e+00,
         1.16118421e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -8.69155475e-03,
         0.00000000e+00, -6.92712862e-03, -8.81024752e-03,
         6.85714286e+00,  7.43243243e-01,  1.04792332e+00,
        -1.10492179e-02, -2.36630383e-04, -1.87292460e-02,
        -2.17373037e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -6.66666667e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.04792332e+00,
         1.16118421e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -2.86341770e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.00000000e+00],
       [-1.39258652e-02,  0.00000000e+00,  0.00000000e+00,
         5.05586592e-01,  0.00000000e+00,  5.58928571e+00,
         0.00000000e+00,  7.64227642e-01,  0.00000000e+00,
         9.27631579e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -8.69155475e-03,
         0.00000000e+00, -6.92712862e-03, -8.81024752e-03,
         5.58928571e+00,  5.51351351e-01,  8.21086262e-01,
        -1.10492179e-02, -2.36630383e-04, -1.87292460e-02,
        -2.17373037e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -6.66666667e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  8.21086262e-01,
         9.27631579e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -2.86341770e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.00000000e+00]])

## 5.- Arbol de decision

In [44]:
from sklearn.tree import DecisionTreeClassifier

MAX_DEPTH = 20

# 1. Entrenar el modelo con los datos sin escalar
clf_tree = DecisionTreeClassifier(max_depth=MAX_DEPTH, random_state=42)
clf_tree.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=20, random_state=42)

In [45]:
clf_tree_scaled = DecisionTreeClassifier(max_depth=MAX_DEPTH,random_state=42)
clf_tree_scaled.fit(x_train_scaled,y_train)

DecisionTreeClassifier(max_depth=20, random_state=42)

### Comenzar predicioendo con el propio dataset con el que se ha entrenado el algoritmo (train_set), suele ser interesante para comprobar si esta produciendo overfitting

In [46]:
# Prediciendo con el dataset de entrenamiento
y_train_pred = clf_tree.predict(x_train)
y_train_prep_pred = clf_tree_scaled.predict(x_train_scaled)

In [47]:
evaluate(y_train_pred,y_train,y_train_prep_pred,y_train,f1_score)

f1_score WITHOUT preparation: 0.9593915432471419
f1_score WITH preparation: 0.9995253096033468